### PR TITLE
Fine tuning

### PR DESCRIPTION
**Pull request by rayrutjes**

### CODE REVIEW

**Comment by redox** [comment]
Yeah, not sure why we had that JSON polyfill.

**Comment by rayrutjes** [comment]
removed it because it was raising some warnings because some "eval" functions were used there ;)

**Comment by Haroenv** [comment]
@redox I assume it was in algoliasearch originally for IE7 compat?

**Comment by redox** [comment]
> @redox I assume it was in algoliasearch originally for IE7 compat?

Yes most probably!

**Pull request merged**
