### PR TITLE
Fixed the delete icon behaviour.

### PR DESCRIPTION
**Pull request by rayrutjes**
There you go, the delete icon appears again ^^.

### CODE REVIEW

**Comment by redox** [comment]
Oh, didn't get that one! :+1:

**Comment by redox** [comment]
I'll release it shortly :zzz:

**Comment by rayrutjes** [comment]
yup, I've got my own build, no worries : )

We still got the fix the little gap between the twitter typeahead and the actual search field.

**Comment by redox** [comment]
> We still got the fix the little gap between the twitter typeahead and the actual search field.

True, need to fine-tune it :)

**Pull request merged**
