### PR TITLE
Alternative approach to a shortcut for global search

### PR DESCRIPTION
**Pull request by Jackymancs4**
Trying to address #69

schermata 2018-02-11 alle 15 34 43 2

Tested mainly on Firefox 58

### CODE REVIEW

**Comment by Jackymancs4** [comment]
Well, I am not sure I get what you mean.. this is a PR and it implements what can be seen in the screenshot, the key binding and additional text.

**Comment by rayrutjes** [comment]
> Well, I am not sure I get what you mean.. this is a PR and it implements what can be seen in the screenshot, the key binding and additional text.

.........indeed, I thought it was an issue :)

**Comment by Jackymancs4** [comment]
Hello @rayrutjes 
Any update on this?

**Comment by rayrutjes** [comment]
Just released in 1.7.0 thank you @Jackymancs4

**Pull request merged**
