### PR TITLE
feat(autocomplete): add an option to search globally instead of in repo

### PR DESCRIPTION
**Pull request by rayrutjes**
Closes: #69 

This adds an option to search everywhere instead of in the current repository.

image

### CODE REVIEW

**Comment by Jackymancs4** [comment]
Hello @rayrutjes 
Any plan on merging this?
Since it's definitely a nice feat and something I would use!

**Comment by rayrutjes** [comment]
I'm not convinced about this PR @Jackymancs4 .
It seems like you can easily delete the current repository context by hitting the return key.

I do realize this PR is convenient when you already typed something and you want to search in all repositories, but I don't want it to affect all other users that would now have to hit the arrow down key once more to get to their result.

**Comment by Jackymancs4** [comment]
I see. Well, it's a good point..
Would you mind to take a look at #76?
I think it works pretty well, and the whole feature (in a way or another) greatly improve my workflow.

**Comment by rayrutjes** [comment]
Solved by #76 .

**Pull request closed without merging**
