### PR TITLE
Adjustments

### PR DESCRIPTION
**Pull request by rayrutjes**

### CODE REVIEW

**Comment by Shipow** [comment]
Jonas is also on it, please sync together :p

**Comment by rayrutjes** [comment]
@JonasBa takes it over ;)

**Comment by JonasBa** [comment]
I changed the header color to cater for the light layout, widths should be fine now. Is there a way we can distinguish from the gh-dark and gh-light layout?

**Comment by Shipow** [comment]
yes apparently there is a class on the header: `header-dark`

**Pull request merged**
